/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cookbook_webgenie_webwrapper_CakePan */

#ifndef _Included_com_cookbook_webgenie_webwrapper_CakePan
#define _Included_com_cookbook_webgenie_webwrapper_CakePan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cookbook_webgenie_webwrapper_CakePan
 * Method:    nBakePi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_cookbook_webgenie_webwrapper_CakePan_nBakePi
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
